import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";
import CodeSnippetSheet from "@/components/code-snippet-sheet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Code Saver App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full w-full relative">
          <Toaster />
          <CodeSnippetSheet />
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
